/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ASlider: typeof import('@arco-design/web-vue')['Slider']
    ASplit: typeof import('@arco-design/web-vue')['Split']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATrigger: typeof import('@arco-design/web-vue')['Trigger']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
    Game: typeof import('./src/components/Game.vue')['default']
    Record: typeof import('./src/components/Record.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Setting.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
